development:
  adapter: sqlite3
  encoding: utf8
  database: development.sqlite3

test:
  adapter: sqlite3
  encoding: utf8
  database: test.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:
